import { parseMemoryTelemetryEvent } from "./schema.js";
import type { MemoryTelemetryEvent } from "./types.js";

export type MemoryTelemetryEventWithoutId = Omit<MemoryTelemetryEvent, "eventId"> & {
  eventId?: undefined;
};

export type MemoryTelemetryEventInput = MemoryTelemetryEvent | MemoryTelemetryEventWithoutId;

export type MemoryTelemetryEventIdFactory = (
  event: Readonly<MemoryTelemetryEventWithoutId>
) => string;

export type MemoryTelemetryTransport = (
  events: readonly MemoryTelemetryEvent[]
) => Promise<void>;

export type MemoryTelemetryRetryPolicy = {
  /** Total transport attempts, including the initial attempt. */
  maxAttempts?: number;
  initialDelayMs?: number;
  maxDelayMs?: number;
  multiplier?: number;
};

export type MemoryTelemetryScheduler = {
  setTimeout(callback: () => void, delayMs: number): unknown;
  clearTimeout(handle: unknown): void;
};

export type MemoryTelemetryDeliveryFailure = {
  events: readonly MemoryTelemetryEvent[];
  attempts: number;
  error: unknown;
  bufferedEventCount: number;
};

export type MemoryTelemetryClientOptions = {
  transport: MemoryTelemetryTransport;
  /**
   * No event id is generated by default. Supplying this factory explicitly lets
   * an integration derive a stable id from its own trace/span/operation identity.
   */
  eventIdFactory?: MemoryTelemetryEventIdFactory;
  maxBatchSize?: number;
  /** Set to 0 to disable interval-based flushing. */
  flushIntervalMs?: number;
  maxBufferedEvents?: number;
  retry?: MemoryTelemetryRetryPolicy;
  delay?: (delayMs: number) => Promise<void>;
  scheduler?: MemoryTelemetryScheduler;
  onDeliveryFailure?: (failure: MemoryTelemetryDeliveryFailure) => void;
};

type BufferedEvent = {
  event: MemoryTelemetryEvent;
  ordinal: number;
};

type ResolvedRetryPolicy = Required<MemoryTelemetryRetryPolicy>;

const DEFAULT_MAX_BATCH_SIZE = 25;
const DEFAULT_FLUSH_INTERVAL_MS = 1_000;
const DEFAULT_MAX_BUFFERED_EVENTS = 1_000;

const defaultScheduler: MemoryTelemetryScheduler = {
  setTimeout: (callback, delayMs) => globalThis.setTimeout(callback, delayMs),
  clearTimeout: (handle) => globalThis.clearTimeout(handle as ReturnType<typeof setTimeout>)
};

function defaultDelay(delayMs: number): Promise<void> {
  return new Promise((resolve) => {
    globalThis.setTimeout(resolve, delayMs);
  });
}

function requirePositiveInteger(value: number, name: string): number {
  if (!Number.isInteger(value) || value <= 0) {
    throw new RangeError(`${name} must be a positive integer.`);
  }

  return value;
}

function requireNonnegativeInteger(value: number, name: string): number {
  if (!Number.isInteger(value) || value < 0) {
    throw new RangeError(`${name} must be a nonnegative integer.`);
  }

  return value;
}

function resolveRetryPolicy(policy: MemoryTelemetryRetryPolicy = {}): ResolvedRetryPolicy {
  const resolved = {
    maxAttempts: policy.maxAttempts ?? 3,
    initialDelayMs: policy.initialDelayMs ?? 100,
    maxDelayMs: policy.maxDelayMs ?? 1_000,
    multiplier: policy.multiplier ?? 2
  };

  requirePositiveInteger(resolved.maxAttempts, "retry.maxAttempts");
  requireNonnegativeInteger(resolved.initialDelayMs, "retry.initialDelayMs");
  requireNonnegativeInteger(resolved.maxDelayMs, "retry.maxDelayMs");

  if (!Number.isFinite(resolved.multiplier) || resolved.multiplier < 1) {
    throw new RangeError("retry.multiplier must be a finite number greater than or equal to 1.");
  }

  if (resolved.maxDelayMs < resolved.initialDelayMs) {
    throw new RangeError("retry.maxDelayMs must be greater than or equal to retry.initialDelayMs.");
  }

  return resolved;
}

function freezeRecursively<T>(value: T): T {
  if (value && typeof value === "object" && !Object.isFrozen(value)) {
    for (const child of Object.values(value)) {
      freezeRecursively(child);
    }
    Object.freeze(value);
  }

  return value;
}

export class MissingMemoryTelemetryEventIdError extends Error {
  constructor() {
    super("Memory telemetry events require an eventId or an explicit eventIdFactory.");
    this.name = "MissingMemoryTelemetryEventIdError";
  }
}

export class MemoryTelemetryBufferOverflowError extends Error {
  readonly maxBufferedEvents: number;

  constructor(maxBufferedEvents: number) {
    super(`Memory telemetry buffer reached its ${maxBufferedEvents}-event limit.`);
    this.name = "MemoryTelemetryBufferOverflowError";
    this.maxBufferedEvents = maxBufferedEvents;
  }
}

export class MemoryTelemetryClientClosedError extends Error {
  constructor() {
    super("Memory telemetry client is closed and cannot accept new events.");
    this.name = "MemoryTelemetryClientClosedError";
  }
}

export class MemoryTelemetryDeliveryError extends Error {
  readonly failure: MemoryTelemetryDeliveryFailure;
  override readonly cause: unknown;

  constructor(failure: MemoryTelemetryDeliveryFailure) {
    super(`Memory telemetry delivery failed after ${failure.attempts} attempt(s).`);
    this.name = "MemoryTelemetryDeliveryError";
    this.failure = failure;
    this.cause = failure.error;
  }
}

/**
 * A small, runtime-neutral telemetry emitter. It owns no network client and
 * removes events from memory only after the injected transport confirms delivery.
 */
export class MemoryTelemetryClient {
  private readonly transport: MemoryTelemetryTransport;
  private readonly eventIdFactory?: MemoryTelemetryEventIdFactory;
  private readonly maxBatchSize: number;
  private readonly flushIntervalMs: number;
  private readonly maxBufferedEvents: number;
  private readonly retry: ResolvedRetryPolicy;
  private readonly delay: (delayMs: number) => Promise<void>;
  private readonly scheduler: MemoryTelemetryScheduler;
  private readonly onDeliveryFailure?: (failure: MemoryTelemetryDeliveryFailure) => void;
  private readonly buffer: BufferedEvent[] = [];

  private nextOrdinal = 0;
  private flushTail: Promise<void> = Promise.resolve();
  private timerHandle: unknown;
  private timerScheduled = false;
  private closed = false;
  private lastFailure: MemoryTelemetryDeliveryFailure | undefined;

  constructor(options: MemoryTelemetryClientOptions) {
    this.transport = options.transport;
    this.eventIdFactory = options.eventIdFactory;
    this.maxBatchSize = requirePositiveInteger(
      options.maxBatchSize ?? DEFAULT_MAX_BATCH_SIZE,
      "maxBatchSize"
    );
    this.flushIntervalMs = requireNonnegativeInteger(
      options.flushIntervalMs ?? DEFAULT_FLUSH_INTERVAL_MS,
      "flushIntervalMs"
    );
    this.maxBufferedEvents = requirePositiveInteger(
      options.maxBufferedEvents ?? DEFAULT_MAX_BUFFERED_EVENTS,
      "maxBufferedEvents"
    );
    this.retry = resolveRetryPolicy(options.retry);
    this.delay = options.delay ?? defaultDelay;
    this.scheduler = options.scheduler ?? defaultScheduler;
    this.onDeliveryFailure = options.onDeliveryFailure;
  }

  get bufferedEventCount(): number {
    return this.buffer.length;
  }

  get isClosed(): boolean {
    return this.closed;
  }

  get lastDeliveryFailure(): MemoryTelemetryDeliveryFailure | undefined {
    return this.lastFailure;
  }

  getBufferedEvents(): readonly MemoryTelemetryEvent[] {
    return this.buffer.map(({ event }) => event);
  }

  async emit(input: MemoryTelemetryEventInput): Promise<MemoryTelemetryEvent> {
    if (this.closed) {
      throw new MemoryTelemetryClientClosedError();
    }

    const event = this.prepareEvent(input);

    if (this.buffer.length >= this.maxBufferedEvents) {
      throw new MemoryTelemetryBufferOverflowError(this.maxBufferedEvents);
    }

    this.buffer.push({ event, ordinal: this.nextOrdinal });
    this.nextOrdinal += 1;

    if (this.buffer.length >= this.maxBatchSize) {
      await this.flush();
    } else {
      this.scheduleFlush();
    }

    return event;
  }

  /** Flushes every event accepted before this call, preserving acceptance order. */
  flush(): Promise<void> {
    this.cancelScheduledFlush();
    const throughOrdinal = this.nextOrdinal - 1;
    const operation = this.flushTail.then(() => this.drainThrough(throughOrdinal));

    // Keep later flushes serialized even when this caller observes a rejection.
    this.flushTail = operation.catch(() => undefined);

    return operation.then(() => {
      if (!this.closed && this.buffer.length > 0) {
        this.scheduleFlush();
      }
    });
  }

  /** Stops accepting events and attempts to deliver everything already accepted. */
  async close(): Promise<void> {
    this.closed = true;
    this.cancelScheduledFlush();
    await this.flush();
  }

  private prepareEvent(input: MemoryTelemetryEventInput): MemoryTelemetryEvent {
    let candidate: MemoryTelemetryEvent;

    if (input.eventId === undefined) {
      if (!this.eventIdFactory) {
        throw new MissingMemoryTelemetryEventIdError();
      }

      const eventId = this.eventIdFactory(input);
      candidate = { ...input, eventId } as MemoryTelemetryEvent;
    } else {
      candidate = input;
    }

    return freezeRecursively(parseMemoryTelemetryEvent(candidate));
  }

  private scheduleFlush(): void {
    if (
      this.closed
      || this.flushIntervalMs === 0
      || this.timerScheduled
      || this.buffer.length === 0
    ) {
      return;
    }

    this.timerScheduled = true;
    this.timerHandle = this.scheduler.setTimeout(() => {
      this.timerScheduled = false;
      this.timerHandle = undefined;

      // flush records and reports terminal failures; the timer has no caller to reject to.
      void this.flush().catch(() => undefined);
    }, this.flushIntervalMs);
  }

  private cancelScheduledFlush(): void {
    if (!this.timerScheduled) {
      return;
    }

    this.scheduler.clearTimeout(this.timerHandle);
    this.timerHandle = undefined;
    this.timerScheduled = false;
  }

  private async drainThrough(throughOrdinal: number): Promise<void> {
    while (this.buffer.length > 0 && this.buffer[0].ordinal <= throughOrdinal) {
      const items = this.buffer
        .slice(0, this.maxBatchSize)
        .filter(({ ordinal }) => ordinal <= throughOrdinal);
      const events = Object.freeze(items.map(({ event }) => event));

      await this.deliver(events);
      this.buffer.splice(0, items.length);
      this.lastFailure = undefined;
    }
  }

  private async deliver(events: readonly MemoryTelemetryEvent[]): Promise<void> {
    let lastError: unknown;
    let attempts = 0;

    for (let attempt = 1; attempt <= this.retry.maxAttempts; attempt += 1) {
      attempts = attempt;
      try {
        await this.transport(events);
        return;
      } catch (error) {
        lastError = error;

        if (attempt < this.retry.maxAttempts) {
          const delayMs = Math.min(
            this.retry.maxDelayMs,
            this.retry.initialDelayMs * (this.retry.multiplier ** (attempt - 1))
          );
          try {
            await this.delay(delayMs);
          } catch (delayError) {
            lastError = delayError;
            break;
          }
        }
      }
    }

    const failure = Object.freeze<MemoryTelemetryDeliveryFailure>({
      events,
      attempts,
      error: lastError,
      bufferedEventCount: this.buffer.length
    });

    this.lastFailure = failure;
    try {
      this.onDeliveryFailure?.(failure);
    } catch {
      // A reporting hook must not replace the original delivery failure.
    }

    throw new MemoryTelemetryDeliveryError(failure);
  }
}

export function createMemoryTelemetryClient(
  options: MemoryTelemetryClientOptions
): MemoryTelemetryClient {
  return new MemoryTelemetryClient(options);
}
